%% SG_autoconversion
% Calculate autoconversion rates used by the SAM single-moment microphysics
% scheme.
%
% Tristan Abbott // Massachusetts Institute of Technology // 03/30/2018
%
%%% Syntax
%   [a, al, ai] = SG_autoconversion(grid, 'tabs', 'qn')
%
%%% Description
% Computes autoconversion rates for liquid and ice clouds. The calculations are
% performed based on the SAM single-moment microphysics scheme.
% Details about the SAM model and microphysics are given in in Appendix A of 
% Khairoutdinov and Randall, 2003: "Cloud Resolving
% Modeling of the ARM Summer 1997 IOP: Model Formulation, Results, 
% Uncertainties, and Sensitivities", _Journal of the Atmospheric Sciences_. 
%
% All inputs can be multidimensional. If multidimensional input
% is given, all inputs must be the same shape and size and the function will
% operate element-wise.
%
%%% Input Arguments
%
% *grid - SAM C-grid struct:*
% A struct containing grid information generated by SG_grid and fields
% added by SG_addVar.
%
% *tabs, qn - names of fields:*
% String keys that can be used to look up absolute temperature and
% cloud water specific humidity.
%
%%% Output Arguments
% *a - total autoconversion rate:*
% Total autoconversion rate in both liquid and ice cloud. Has units of 1/s.
%
% *al - liquid cloud autoconversion rate:*
% Autoconversion rate in liquid cloud. Has units of 1/s.
%
% *ai - ice cloud autoconversion rate:*
% Autoconversion rate in ice cloud. Has units of 1/s.
%
%%% Source code
function [a, al, ai] = SG_autoconversion(grid, tabs, qn)

    % Add global variables
    global SOM_alpha;
    global SOM_beta;
    global SOM_q_co;
    global SOM_q_io;
    global SOM_T_00n;
    global SOM_T_0n;
    
    % Compute mixing ratios of different forms of cloud water
    on = SOM_omega(grid.(tabs), SOM_T_0n, SOM_T_00n);
    qc = on.*grid.(qn);
    qi = (1 - on).*grid.(qn);
    
    % Compute autoconversion rates
    al = max(0, SOM_alpha.*(qc - SOM_q_co));
    ai = max(0, SOM_beta.*exp(0.025*(grid.(tabs) - 273.16)).*(qi - SOM_q_io));
    a = al + ai;

end
