%% SG_addPPert
% Add pressure perturbations to pressure field.
%
% Tristan Abbott // Massachusetts Institute of Technology // 11/14/2017
%
%%% Syntax
%   SG_addPPert(grid, PP);
%
%%% Description
% Compute a 3D pressure field including perturbations.
%
%%% Input Arguments
% *grid - SAM C-grid struct:*
% A struct containing grid information generated by SG_grid and fields
% added by SG_addVar.
%
% *PP - pressure perturbations:*
% Field containing pressure perturbations. Should be the same format as a
% field accepted as scalars by SG_addVar.
%
%%% Output Arguments
% None, but pressure anomalies are added to grid.pp.
%
function SG_addPPert(grid, PP)
    grid.pp = grid.pp + SG_addVar(PP, 's');
end