%% SG_hL
% Compute liquid/ice moist static energy at tracer cell centers
%
% Tristan Abbott // Massachusetts Institute of Technology // 11/14/2017
%
%%% Syntax
%   hL = SG_hL(grid, 'T', 'qn', 'qp');
%
%%% Description
% Compute the liquid/ice frozen moist static energy used by SAM,
% $$
% h_L = c_p T + g z - L_v q_l - L_s q_i,
% $$
% at tracer cell centers.
%
%%% Input Arguments
% *grid - SAM C-grid struct:*
% A struct containing grid information generated by SG_grid and fields
% added by SG_addVar.
%
% *T, qn qp - names of fields:*
% String keys that can be used to look up temperature, non-precipitating
% condensate, and precipitating condensate fields.
%
%%% Output Arguments
%
% *hL - FMSE:*
% Array containing frozen moist static energy at tracer cell centers.
%

function hL = SG_hL(grid, T, qn, qp)
    d = size(grid.(T));
    z = repmat(grid.z, [1 d(2) d(3)]);
    hL = SAM_hL(grid.(T), z, grid.(qn), grid.(qp));
end