%% SG_meanProfile
% Compute a domain-mean profile
%
% Tristan Abbott // Massachusetts Institute of Technology // 11/14/2017
%
%%% Syntax
%   prof = SG_meanProfile(grid, 'T');
%
%%% Description
% Compute domain mean profiles of quantities held in a SG grid data
% structure.
%
%%% Input Arguments
% *grid - SAM C-grid struct:*
% A struct containing grid information generated by SG_grid and fields
% added by SG_addVar.
%
% *s - name of quantity being integrated:*
% Key used to look up the field being averaged.
%
%%% Output Arguments
%
% *prof - mean profile:*
% 1D array containing the domain-mean profile

function prof = SG_meanProfile(grid, s)
    n = size(grid.(s));
    prof = mean(reshape(grid.(s), [n(1), n(2)*n(3)]), 2);
end