%% SG_uvw2v
% Convert velocities in mass transport form back to normal velocities
%
% Tristan Abbott // Massachusetts Institute of Technology // 1/31/2018
%
%%% Syntax
%   [u,v,w] = SG_uvw2v(grid, 'um', 'vm', 'wm');
%
%%% Description
% Converts mass transports to velocities:
% $$
% u_i = \frac{um_i dx_i}{\rho}.
% $$
% This reverses the operation applied in SG_uwv2m.
%
%%% Input Arguments
% *grid - SAM C-grid struct:*
% A struct containing grid information generated by SG_grid and fields
% added by SG_addVar.
%
% 'um,vm,wm - names of fields:*
% String keys that can be used to look up the three components of the
% mass transport field.
%
%%% Output Arguments
%
% *u, v, w - velocities*
%

function [u,v,w] = SG_uvw2v(grid, um, vm, wm)
    u = zeros(size(grid.(um)));
    v = zeros(size(grid.(vm)));
    w = zeros(size(grid.(wm)));
    for kk = 1:grid.nzm
        u(kk,:,:) = grid.(um)(kk,:,:)*grid.dx/grid.rho(kk);
        v(kk,:,:) = grid.(vm)(kk,:,:)*grid.dy/grid.rho(kk);
        w(kk,:,:) = grid.(wm)(kk,:,:)*grid.dz/grid.rhoi(kk);
    end
end
