%% SG_uvw2m
% Convert velocities to mass transports
%
% Tristan Abbott // Massachusetts Institute of Technology // 1/31/2018
%
%%% Syntax
%   [um,vm,wm] = SG_uvw2m(grid, 'u', 'v', 'w');
%
%%% Description
% Converts velocities to mass transports:
% $$
% um_i = \frac{u_i}{dx_i} \rho.
% $$
% This is similar to what is done in adams() before advecting scalars,
% except that here, the time step is not used in the nondimensionalization.
%
%%% Input Arguments
% *grid - SAM C-grid struct:*
% A struct containing grid information generated by SG_grid and fields
% added by SG_addVar.
%
% 'u,v,w - names of fields:*
% String keys that can be used to look up the three components of the
% velocity field.
%
%%% Output Arguments
%
% *um, vm, wm - mass transports*
%

function [um,vm,wm] = SG_uvw2m(grid, u, v, w)
    
    um = zeros(size(grid.(u)));
    vm = zeros(size(grid.(v)));
    wm = zeros(size(grid.(w)));
    for kk = 1:grid.nzm
        um(kk,:,:) = grid.(u)(kk,:,:)*grid.rho(kk)/grid.dx;
        vm(kk,:,:) = grid.(v)(kk,:,:)*grid.rho(kk)/grid.dy;
        wm(kk,:,:) = grid.(w)(kk,:,:)*grid.rhoi(kk)/grid.dz;
    end
end
