%% SG_wAtScalar
% Compute vertical velocities at scalar cell centers
%
% Tristan Abbott // Massachusetts Institute of Technology // 1/28/2018
%
%%% Syntax
%   w_est = SG_wAtScalar(grid, 'w', 'average');
%
%%% Description
% Estimate vertical velocities at tracer cell centers.
%
%%% Input Arguments
% *grid - SAM C-grid struct:*
% A struct containing grid information generated by SG_grid and fields
% added by SG_addVar.
%
% *T, qn qp - names of fields:*
% String keys that can be used to look up temperature, non-precipitating
% condensate, and precipitating condensate fields.
%
% *interpopt - interpolation option:*
% Must be one of 'average': average w at top and bottom cell faces
%%% Output Arguments
%
% *w_est - vertical velocity:*
% Array containing vertical velocity estimates at tracer cell centers.
%

function w_est = SG_hL(grid, w, interpopt)
    
    switch lower(interpopt)
        case 'average'
            w_est = average(grid, w);
        otherwise
            error('SG_wAtScalar: unknown interpolation option %s',...
                lower(interpopt))
    end
    
end

function w_est = average(grid, w)

    w_est = 0.5*(grid.(w)(1:end-1,:,:) + grid.(w)(2:end,:,:));

end
