#!/bin/bash
echo "#!/bin/bash" > setpath
echo "# Autogenerated by install_dependencies.sh" >> setpath
echo "export LD_LIBRARY_PATH=${ZDIR}/lib:${H5DIR}/lib:${NCDIR}/lib:${NFDIR}/lib:$LD_LIBRARY_PATH" >> setpath
