%% rad_cam_wrapper
% MATLAB interface to CAM radiation scheme used in SAM

nx = 16;
ny = 16;
nzm = 16;
nz = nzm + 1;

zi = 1:nz;
presi = 1:nz;
day = 120;
day0 = 80.5;
dt = 8;
nrad = 1;
nstep = 6;
doperpetual = -1;
ocean = 1;
dolongwave = 1;
doshortwave = 1;
doseasons = -1;
dosolarconstant = -1;
doradhomo = -1;
zenith_angle = 0.5;
solar_constant = 450;
latitude = 20*ones(nx,ny);
longitude = 10*ones(nx,ny);
sstxy = zeros(nx,ny);
rho = ones(nzm,1);
tabs = 300*ones(nx,ny,nzm);
qv = 0.0001*rand(nx,ny,nzm);
qcl = 0.0001*rand(nx,ny,nzm);
qci = 0.0001*rand(nx,ny,nzm);

qrad = mx_rad_cam_wrapper(...
    zi, ...
    presi, ...
    day, ...
    day0, ...
    dt, ...
    nrad, ...
    nstep, ...
    doperpetual, ...
    ocean, ...
    dolongwave, ...
    doshortwave, ...
    doseasons, ...
    dosolarconstant, ...
    doradhomo, ...
    zenith_angle, ...
    solar_constant, ...
    latitude, ...
    longitude, ...
    sstxy, ...
    rho, ...
    tabs, ...
    qv, ...
    qcl, ...
    qci);