#!/bin/bash
# Autogenerated by install_dependencies.sh
export LD_LIBRARY_PATH=/data/thabbott/matlab/SAMtools/rad_cam_wrapper/zlib/lib:/data/thabbott/matlab/SAMtools/rad_cam_wrapper/hdf5/lib:/data/thabbott/matlab/SAMtools/rad_cam_wrapper/netcdf-c/lib:/data/thabbott/matlab/SAMtools/rad_cam_wrapper/netcdf-fortran/lib:/data/thabbott/matlab/SAMtools/rad_cam_wrapper/netcdf-c/lib:/data/thabbott/matlab/SAMtools/rad_cam_wrapper/hdf5/lib:/data/thabbott/matlab/SAMtools/rad_cam_wrapper/zlib/lib:
